local function detector()
    game.Players.PlayerAdded:Connect(function(plr)
        if not table.find(whitelisted, plr.UserId) then 
            game:Shutdown()
        end
    end)
    
    for _, plr in next, game.Players:GetPlayers() do 
        if plr.Name ~= game.Players.LocalPlayer.Name then 
            if not table.find(whitelisted, plr.UserId) then 
                game:Shutdown()
            end
        end    
    end
end

if not game:IsLoaded() then game.Loaded:Wait() end
game.Players.LocalPlayer.PlayerGui:WaitForChild('Menu')
game:GetService("ReplicatedStorage").SpawnCharacter:FireServer()
detector()
task.wait(1.5)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-683, 68, -713)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-683, 68, -750)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-571, 68, -749)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-627.397, 71.0585, -675.863) 
wait(.2)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-571, 68, -713)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-643, 68, -705) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-612, 68, -711)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-617, 68, -732)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-608, 68, -749)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-627.397, 71.0585, -675.863) 
wait(.2)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-655, 69, -737) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-646, 68, -751) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-627.397, 71.0585, -675.863) 
wait(.2)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-598, 68, -722)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-599, 68, -741)
wait(.2)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-627.397, 71.0585, -675.863)
wait(.3)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1168, 71, 170) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1152, 72, 171) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1114, 71, 209) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1114, 71, 223) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1141, 71, 262) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1090.166, 71.249, 217.003) 
wait(.2)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1148, 71, 262) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1155, 71, 262) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1139, 71, 223) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1139, 71, 209) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1158, 71, 209) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1090.166, 71.249, 217.003) 
wait(.2)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1158, 71, 222) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1176, 71, 223) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1176, 71, 209) 
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1129, 71, 169) 
wait(0.1)
game:GetService("VirtualInputManager"):SendKeyEvent(true, "E", false, game)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1090.166, 71.249, 217.003)
wait(0.5)
game:GetService('TeleportService'):TeleportToPlaceInstance(game.PlaceId, game.JobId, game:GetService'Players'.LocalPlayer) 
